export const FETCH_PRODUCTS_DATA_STARTED = "FETCH_PRODUCTS_DATA_STARTED";
export const FETCH_PRODUCTS_DATA_COMPLETED = "FETCH_PRODUCTS_DATA_COMPLETED";
export const FETCH_PRODUCTS_DATA_FAILED = "FETCH_PRODUCTS_DATA_FAILED";

export const REINITIALIZE_STATE = "REINITIALIZE_STATE";

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS";
